enum ROLE {
  ADMIN = "ADMIN",
  USER = "USER",
}
enum STATE {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}
enum RESOURCETYPE {
  GPU = "GPU",
  GCU = "GCU",
}
enum STATUSREQUEST {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}
enum REQUESTSTATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  QUEUED = "QUEUED",
  COMPLETED = "COMPLETED",
}

export { ROLE, STATE, RESOURCETYPE, REQUESTSTATUS, STATUSREQUEST };
