enum ROLE {
  ADMIN = "ADMIN",
  USER = "USER",
}
enum STATE {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}
enum RESOURCETYPE {
  GPU = "GPU",
  CPU = "CPU",
  RAM = "RAM",
  DISK = "DISK",
}
enum STATUSREQUEST {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}
enum REQUESTSTATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  QUEUED = "QUEUED",
  COMPLETED = "COMPLETED",
}
enum RESOURCESTATUS {
  AVAILABLE = "available",
  ALLOCATED = "allocated",
  MAINTENANCE = "maintenance",
}
export const RESOURCESTATUS_TRANSLATION = {
  [RESOURCESTATUS.ALLOCATED]: "Đang được sử dụng",
  [RESOURCESTATUS.AVAILABLE]: "Có sẵn",
  [RESOURCESTATUS.MAINTENANCE]: "Bảo trì",
};
enum APPROVALSTATUS {
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  QUEUED = "QUEUED",
}

export {
  ROLE,
  STATE,
  RESOURCETYPE,
  REQUESTSTATUS,
  STATUSREQUEST,
  RESOURCESTATUS,
  APPROVALSTATUS,
};
