enum ROLE {
  ADMIN = "ADMIN",
  USER = "USER",
}
enum STATE {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}
enum RESOURCETYPE {
  GPU = "GPU",
  GCU = "GCU",
  RAM = "RAM",
  DISK = "DISK",
}
enum STATUSREQUEST {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}
enum REQUESTSTATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  QUEUED = "QUEUED",
  COMPLETED = "COMPLETED",
}
enum RESOURCESTATUS {
  AVAILABLE = "AVAILABLE",
  ALLOCATED = "ALLOCATED",
  MAINTENANCE = "MAINTENANCE",
}
enum APPROVALSTATUS {
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  QUEUED = "QUEUED",
}

export {
  ROLE,
  STATE,
  RESOURCETYPE,
  REQUESTSTATUS,
  STATUSREQUEST,
  RESOURCESTATUS,
  APPROVALSTATUS,
};
